name: Code Coverage

on:
  push:
    branches:
      - github-automation

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install OpenBLAS
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev

      - name: Inspect Lib Path
        run: ls -alh /usr/lib/x86_64-linux-gnu

      - name: Download and extract TASSEL test data
        run: |
          curl -L \
            -o tassel_test_data_v1.tar.gz \
            https://github.com/maize-genetics/tassel_test_data/releases/download/v1.0.0/tassel_test_data_v1.tar.gz

          tar -xzvf tassel_test_data_v1.tar.gz

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Run tests & generate Kover coverage report
        run: ./gradlew clean test koverXmlReport --continue
        continue-on-error: true
        env:
          JAVA_TOOL_OPTIONS: >
            -Djava.library.path=/usr/lib/x86_64-linux-gnu

      - name: Upload HTML test report
        uses: actions/upload-artifact@v3
        with:
          name: html-test-report
          path: build/reports/tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_GLOBAL_TOKEN }}
          slug: maize-genetics/tassel
          files: build/reports/kover/report.xml
