name: Site Builder and Deployment
on:
  workflow_run:
    workflows: ["jDeploy CI with Gradle"]
    types:
      - completed
    branches: [main, master]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Wait for Publish TASSEL to Maven Central workflow
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          check-name: 'maven-publish'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
