name: Publish TASSEL to Maven Central

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*'
      - '*.*.*'
    branches: [main, master]

jobs:

  maven-publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{secrets.TASSEL_MAVEN}}
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Publish to Maven Central Repository
        run: ./gradlew jreleaserConfig && ./gradlew clean && ./gradlew publish && ./gradlew jreleaserFullRelease -Dorg.gradle.jvmargs=\"-Xmx8g\"
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USER }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_TOKEN }}
          GPG_SIGNING_KEY: ${{ secrets.ORG_GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.ORG_GPG_SIGNING_PASSWORD }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.ORG_GPG_SIGNING_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.ORG_GPG_SIGNING_PASSWORD }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.ORG_GPG_PUBLIC_KEY }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.TASSEL_MAVEN }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.SONATYPE_USER }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.SONATYPE_TOKEN }}


